version: '3.7'
services:
    app:
        image: laravel-app
        build:
            args:
                user: adsonsouza
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - adson_cotacoes
        depends_on:
            - mysql
            - redis
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./.docker/nginx/:/etc/nginx/conf.d/
        networks:
            - adson_cotacoes
    mysql:
        platform: linux/x86_64
        image: mysql:5.7.38
        command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
        restart: unless-stopped
        #ports:
            #- "3306:3306"
        volumes:
            - "./.docker/dbdata:/var/lib/mysql"
            - "./.docker/init.sql:/data/application/init.sql"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - adson_cotacoes
    redis:
        image: redis:alpine
        networks:
            - adson_cotacoes
networks:
    adson_cotacoes:
        driver: bridge
